name: Build and Test Github Workflow

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: test SSH connection
      run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'echo "This is a successful SSH connection test"'
      


    # - name: Set up Node.js
    #   uses: actions/setup-node@v6
    #   with:
    #     node-version: '20'
    # - name: Install dependencies
    #   run: npm install
    # - name: Run build
    #   run: npm run build
    # - name: Start Application
    #   run: npm start &
    # - name: Test Application
    #   run: |
    #     curl -f http://localhost:3000 || exit 1